# Page settings

baseURL = "https://albertwy.github.io/"
languageCode = "en"
title = "Hi, I'm Yang Wu"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"





[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Yang Wu"
        tagline = "PhD Student"
        avatar = "me.png"







    [params.contact]
        enable = true
        location = "Harbin"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ywu@ir.hit.edu.cn"
        text = "Mail"
        [[params.contact.list]]
        icon = "fab fa-google"
        url = "https://scholar.google.com/citations?user=uMAvnHkAAAAJ&hl=zh-CN"
        text = "Google Scholar"






    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Language"
        [[params.skills.list.items]]
        details = "Python/Java/C++/C"      

        [[params.skills.list]]
        title = "Platform"
        [[params.skills.list.items]]
        details = "Pytorch/Tensorflow"

 







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2019 - Present"
        [[params.education.list]]
        degree = "Exchange Student"
        university = "National University of Singapore"
        dates = "2021 - 2022"
        [[params.education.list]]
        degree = "Master - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2018 - 2019"
        [[params.education.list]]
        degree = "Bachelor - Software Engineering"
        university = "JiLin University"
        dates = "2014 - 2018"






    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "2021 Best Paper Award for IEEE Multimedia"
        body = "IEEE Computer Society Publications Board"
        date = "2021"




    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "Chinese"
        [[params.languages.list]]
        name = "English"









    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Multimodal Sentiment Analysis"
        [[params.interests.list]]
        name = "Large Language Model"









    [params.summary]
        enable = true
        text = "I'm a Ph.D. student in Research Center for Social Computing and Information Retrieval(SCIR), at Harbin Institute of Technology (HIT, China). I am co-advised by Prof. Bing Qin and Prof. Yanyan Zhao. My research interests include multimodal sentiment analysis and large language model."








    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."





    [params.information]
        enable = true


        [[params.information.list]]

        title = "Improving Cross-Task Generalization with Step-by-Step Instructions."
        name = "Yang Wu, Yanyan Zhao, Zhongyang Li, Bing Qin, Kai Xiong"        
        publisher = "Arxiv"
        href = "https://arxiv.org/pdf/2305.04429.pdf"
    
        details = "We propose to incorporate the step-by-step instructions to help language models to decompose the tasks, which can provide the detailed and specific procedures for completing the target tasks. The step-by-step instructions are obtained automatically by prompting ChatGPT, which are further combined with the original instructions to tune language models. The extensive experiments on SUP-NATINST show that the high-quality step-by-step instructions can improve cross-task generalization across different model sizes."


        [[params.information.list]]

        title = "Modeling Incongruity between Modalities for Multimodal Sarcasm Detection."
        name = "Yang Wu, Yanyan Zhao, Xin Lu, Bing Qin, Yin Wu, Jian Sheng, Jinlong Li"
        publisher = "2021 Best Paper Award for IEEE Multimedia"
        href = "https://www.computer.org/publications/best-paper-award-winners"

        details = "We propose the incongruity-aware attention network (IWAN), which detects sarcasm by focusing on the word-level incongruity between modalities via a scoring mechanism. This scoring mechanism could assign larger weights to words with incongruent modalities. Experimental results demonstrate the effectiveness of our proposed IWAN model, which not only achieves the state-of-the-art performance on the MUStARD dataset but also offers the advantages of interpretability."

        [[params.information.list]]
        title = "Sentiment Word Aware Multimodal Refinement for Multimodal Sentiment Analysis with ASR Errors."
        name = "Yang Wu, Yanyan Zhao, Hao Yang, Song Chen, Bing Qin, Xiaohuan Cao, Wenting Zhao"
        publisher = "Findings of ACL 2022"
        href = "https://aclanthology.org/2022.findings-acl.109/"

        details = "We propose the sentiment word aware multimodal refinement model (SWRM), which can dynamically refine the erroneous sentiment words by leveraging multimodal sentiment clues.  We conduct extensive experiments on the real-world datasets including MOSI-Speechbrain, MOSI-IBM, and MOSI-iFlytek and the results demonstrate the effectiveness of our model, which surpasses the current state-of-the-art models on three datasets. Furthermore, our approach can be adapted for other multimodal feature fusion models easily. "

        [[params.information.list]]
        title = "A Text-Centered Shared-Private Framework via Cross-Modal Prediction for Multimodal Sentiment Analysis."
        name = "Yang Wu, Zijie Lin, Yanyan Zhao, Bing Qin, Li-Nan ZHU"
        publisher = "Findings of ACL 2021"
        href = "https://aclanthology.org/2021.findings-acl.417/"

        details = "We propose a text-centered shared-private framework (TCSP) for multimodal fusion, which consists of the cross-modal prediction and sentiment regression parts. Experiments on the MOSEI and MOSI datasets demonstrate the effectiveness of our shared-private framework, which outperforms all baselines. Furthermore, our approach provides a new way to utilize the unlabeled data for multimodal sentiment analysis."

        [[params.information.list]]
        title = "Leveraging Multi-modal Interactions among the Intermediate Representations of Deep Transformers for Emotion Recognition"
        name = "Yang Wu, Zhenyu Zhang, Pai Peng, Yanyan Zhao, Bing Qin"
        publisher = "MuSe'22"
        href = "https://dl.acm.org/doi/abs/10.1145/3551876.3554813"

        details = "Existing end-to-end models typically fuse the uni-modal representations in the last layers without leveraging the multi-modal interactions among the intermediate representations. In this paper, we propose the multi-modal Recurrent Intermediate-Layer Aggregation (RILA) model to explore the effectiveness of leveraging the multi-modal interactions among the intermediate representations of deep pre-trained transformers for end-to-end emotion recognition."

       [[params.information.list]]
        title = "Locate and Combine: A Two-Stage Framework for Aspect-Category Sentiment Analysis."
        name = "Yang Wu, Zhenyu Zhang, Yanyan Zhao and Bing Qin"
        publisher = "NLPCC 2021"
        href = "https://link.springer.com/chapter/10.1007/978-3-030-88480-2_47"

        details = 'We propose a two-stage strategy named Locate-Combine(LC) to utilize the aspect term in a more straightforward way, which ﬁrst locates the aspect term and then takes it as the bridge to ﬁnd the related sentiment words. The experimental results on the public datasets show that the proposed two-stage strategy is effective, which achieves state-of-the-art performance. Furthermore, our model can output explainable intermediate results for model analysis.'




    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/albertwy"
        title = "albertwy"
 





